### ISSUE TITLE
Doesn't show containers and no data in database

### ISSUE THREAD

**Issue by Suleman-Elahi** [oslabs-beta/Dockter#91]
## Prerequisites

- [ x] Using yarn
- [ x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

It should've shown running docker containers

## Current Behavior

No container or log is displayed. Just says "Loading" and that's it.

## Steps to Reproduce

As mentioned in the Readme. After `yarn start` the GUI starts but shows nothing. I am using the `docker101tutorial` docker container.

![image](https://user-images.githubusercontent.com/24384996/100140374-deb10200-2eb6-11eb-93f6-04f74d5aa117.png)

Database:

![image](https://user-images.githubusercontent.com/24384996/100140427-f1c3d200-2eb6-11eb-8244-a1262a5353db.png)

```
alice@alice:~/Dockter$ yarn start
yarn run v1.22.10
$ yarn build
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
[1] 
[1] warn - Tailwind is not purging unused styles because no template paths have been provided.
[1] warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
[1] warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
[0] Hash: fd443e9976e0aa32ce27
[0] Version: webpack 4.44.2
[0] Time: 37144ms
[0] Built at: 25/11/2020 12:29:39 am
[0]                          Asset      Size  Chunks             Chunk Names
[0]             ./app/main.prod.js   736 KiB       0  [emitted]  main
[0] ./app/main.prod.js.LICENSE.txt  55 bytes          [emitted]  
[0] Entrypoint main = ./app/main.prod.js
[0] [./app/main.dev.ts] ./app/main.dev.ts + 8 modules 55.9 KiB {0} [built]
[0]     | ./app/main.dev.ts 7.09 KiB [built]
[0]     | ./app/menu.ts 8.03 KiB [built]
[0]     | ./app/main-process/startup.ts 12.9 KiB [built]
[0]     | ./app/main-process/liveLogs.ts 14.9 KiB [built]
[0]     | ./app/main-process/filter.ts 4.2 KiB [built]
[0]     | ./app/main-process/scroll.ts 7.24 KiB [built]
[0]     | ./app/models/logModel.ts 715 bytes [built]
[0]     | ./app/models/containerModel.ts 295 bytes [built]
[0]     | ./app/main-process/db.ts 531 bytes [built]
[0] [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {0} [built]
[0] [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [dockerode] external "dockerode" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [http] external "http" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [mongoose] external "mongoose" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [stream] external "stream" 42 bytes {0} [built]
[0] [url] external "url" 42 bytes {0} [built]
[0]     + 599 hidden modules
[0] 
[0] WARNING in ./node_modules/electron-debug/index.js 108:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0] 
[0] WARNING in ./node_modules/electron-debug/index.js 109:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0] yarn build-main exited with code 0
[1] Hash: eaaab2ca5e0ce11e4ca8
[1] Version: webpack 4.44.2
[1] Time: 56210ms
[1] Built at: 25/11/2020 12:30:06 am
[1]                                  Asset      Size  Chunks                         Chunk Names
[1]   06b9d19ced8d17f3d5cbd5f1cbb31460.svg   141 KiB          [emitted] [immutable]  
[1]   08f9891a6f44d9546678133ab121fc54.eot  33.5 KiB          [emitted] [immutable]  
[1]   0fea24969112a781acd2463caf03f138.eot   134 KiB          [emitted] [immutable]  
[1] 1008b5226941c24f44681061d347ad5e.woff2  13.2 KiB          [emitted] [immutable]  
[1]  1069ea55beaa0106030287c659732543.woff  16.4 KiB          [emitted] [immutable]  
[1]   10ecefc282f2761808bf26cb335511d5.ttf   200 KiB          [emitted] [immutable]  
[1]   1495f578452eb676f730244d3b9368cd.ttf  33.3 KiB          [emitted] [immutable]  
[1]   371dbce0dd46bd4d2033eb2334f28580.svg   896 KiB          [emitted] [immutable]  
[1]   3a24a60e7f9c6574864a38814fa07533.eot   200 KiB          [emitted] [immutable]  
[1] 3ceb50e7bcafb577367c21b53064e00c.woff2  78.4 KiB          [emitted] [immutable]  
[1]  46fdbd2d897f8824e63c8862af60b24c.woff   102 KiB          [emitted] [immutable]  
[1] c967a94cfbe2b06627ffe7861c741a61.woff2  76.6 KiB          [emitted] [immutable]  
[1]  dc2cbadd690e1d4b2c9c11c8143d027c.woff    90 KiB          [emitted] [immutable]  
[1]   e33e2cf6e02cac2ccb77689015f11c56.svg   730 KiB          [emitted] [immutable]  
[1]   ec82f282c7f54b6370985bdf8406d5b7.ttf   133 KiB          [emitted] [immutable]  
[1]                       renderer.prod.js   532 KiB       0  [emitted]              main
[1]           renderer.prod.js.LICENSE.txt  1.01 KiB          [emitted]              
[1]                              style.css  1.66 MiB       0  [emitted]              main
[1]                          style.css.map  2.81 MiB          [emitted]              
[1] Entrypoint main = style.css renderer.prod.js
[1] [0] multi core-js regenerator-runtime/runtime ./app/index.tsx 52 bytes {0} [built]
[1] [./app/app.global.css] 39 bytes {0} [built]
[1] [./app/constants/routes.json] 19 bytes {0} [built]
[1] [./app/containers/Root.tsx] ./app/containers/Root.tsx + 17 modules 80.8 KiB {0} [built]
[1]     | ./app/containers/Root.tsx 1.42 KiB [built]
[1]     | ./app/Routes.tsx 1.37 KiB [built]
[1]     | ./app/containers/App.tsx 191 bytes [built]
[1]     | ./app/containers/LandingPage.tsx 3.31 KiB [built]
[1]     | ./app/containers/LogsContainer.tsx 1.49 KiB [built]
[1]     |     + 13 hidden modules
[1] [./app/index.tsx] ./app/index.tsx + 6 modules 75.3 KiB {0} [built]
[1]     | ./app/index.tsx 1.52 KiB [built]
[1]     | ./app/store.ts 2.38 KiB [built]
[1]     | ./app/rootReducer.ts 219 bytes [built]
[1]     |     + 4 hidden modules
[1] [./node_modules/connected-react-router/esm/index.js] ./node_modules/connected-react-router/esm/index.js + 5 modules 17.1 KiB {0} [built]
[1]     |    6 modules
[1] [./node_modules/history/esm/history.js] ./node_modules/history/esm/history.js + 2 modules 30.6 KiB {0} [built]
[1]     |    3 modules
[1] [./node_modules/react-redux/es/index.js] ./node_modules/react-redux/es/index.js + 22 modules 49.8 KiB {0} [built]
[1]     |    23 modules
[1] [./node_modules/react-router/esm/react-router.js] ./node_modules/react-router/esm/react-router.js + 2 modules 30.1 KiB {0} [built]
[1]     |    3 modules
[1] [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
[1] [ansi-to-html] external "ansi-to-html" 42 bytes {0} [built]
[1] [dompurify] external "dompurify" 42 bytes {0} [built]
[1] [electron] external "electron" 42 bytes {0} [built]
[1] [html-react-parser] external "html-react-parser" 42 bytes {0} [built]
[1]     + 577 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/postcss-loader/dist/cjs.js??ref--5-2!app/app.global.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/dist/cjs.js?!./app/app.global.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-2!./app/app.global.css 2.62 MiB {0} [built]
[1]         + 18 hidden modules
[1] yarn build-renderer exited with code 0
$ cross-env NODE_ENV=production electron ./app/main.prod.js
DB:  NativeConnection {
  base: Mongoose {
    connections: [ [Circular] ],
    models: { Log: Model { Log }, Container: Model { Container } },
    modelSchemas: { Log: [Schema], Container: [Schema] },
    options: { pluralization: true, [Symbol(mongoose:default)]: true },
    _pluralize: [Function: pluralize],
    Schema: [Function: Schema] {
      reserved: [Object: null prototype],
      Types: [Object],
      ObjectId: [Function]
    },
    model: [Function],
    plugins: [ [Array], [Array], [Array], [Array], [Array] ]
  },
  collections: {
    logs: NativeCollection {
      collection: null,
      Promise: [Function: Promise],
      _closed: false,
      opts: [Object],
      name: 'logs',
      collectionName: 'logs',
      conn: [Circular],
      queue: [],
      buffer: true,
      emitter: [EventEmitter]
    },
    containers: NativeCollection {
      collection: null,
      Promise: [Function: Promise],
      _closed: false,
      opts: [Object],
      name: 'containers',
      collectionName: 'containers',
      conn: [Circular],
      queue: [],
      buffer: true,
      emitter: [EventEmitter]
    }
  },
  models: { Log: Model { Log }, Container: Model { Container } },
  config: { autoIndex: true, useCreateIndex: true, useFindAndModify: false },
  replica: false,
  options: null,
  otherDbs: [],
  relatedDbs: {},
  states: [Object: null prototype] {
    '0': 'disconnected',
    '1': 'connected',
    '2': 'connecting',
    '3': 'disconnecting',
    '99': 'uninitialized',
    disconnected: 0,
    connected: 1,
    connecting: 2,
    disconnecting: 3,
    uninitialized: 99
  },
  _readyState: 2,
  _closeCalled: false,
  _hasOpened: false,
  plugins: [],
  id: 0,
  _listening: false,
  _connectionString: 'mongodb+srv://root:mycluster@cluster0.mcjmn.mongodb.net/dockter?retryWrites=true&w=majority',
  _connectionOptions: {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    promiseLibrary: [Function: Promise],
    driverInfo: { name: 'Mongoose', version: '5.10.12' }
  },
  client: MongoClient {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    s: {
      url: 'mongodb+srv://root:mycluster@cluster0.mcjmn.mongodb.net/dockter?retryWrites=true&w=majority',
      options: [Object],
      promiseLibrary: [Function: Promise],
      dbCache: Map {},
      sessions: Set {},
      writeConcern: undefined,
      namespace: [MongoDBNamespace]
    },
    [Symbol(kCapture)]: false
  },
  '$initialConnection': Promise { <pending> },
  then: [Function],
  catch: [Function],
  _events: [Object: null prototype] {
    open: [Function: bound onceWrapper] { listener: [Function] },
    error: [Function]
  },
  _eventsCount: 2
}
00:30:27.810 › APPIMAGE env is not defined, current application is not an AppImage
Database connected:  mongodb+srv://root:mycluster@cluster0.mcjmn.mongodb.net/dockter?retryWrites=true&w=majority
(node:18103) UnhandledPromiseRejectionWarning: Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:18103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
this is arg {
  container_id: [],
  container_name: [],
  container_image: [],
  status: [],
  stream: [],
  timestamp: { from: '', to: '' },
  host_ip: [],
  host_port: [],
  search: ''
}
(node:18103) UnhandledPromiseRejectionWarning: Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:18103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
this is arg {
  container_id: [],
  container_name: [],
  container_image: [],
  status: [],
  stream: [],
  timestamp: { from: '', to: '' },
  host_ip: [],
  host_port: [],
  log_level: []
}
this is arg {
  container_id: [],
  container_name: [],
  container_image: [],
  status: [],
  stream: [],
  timestamp: { from: '', to: '' },
  host_ip: [],
  host_port: [],
  log_level: []
}
```

## Your Environment

- Node version : v15.2.1
- electron-react-boilerplate version or branch : latest
- Operating System and version : Linux Mint 20

**Comment by samuy** [comment]
Hi @Suleman-Elahi , just to double check are your containers running prior to starting the application?

**Comment by Suleman-Elahi** [comment]
> Hi @Suleman-Elahi , just to double check are your containers running prior to starting the application?

Yeah I was using Airbyte(https://github.com/airbytehq/airbyte/). It was running along with docker101tutorial container when I issued the `yarn start` command.

**Comment by bbrower21** [comment]
Hi @Suleman-Elahi,

Are you using Airbyte as an orchestrator? Our tool specifically interfaces with the Docker Daemon API. So if you have the docker tutorial image running in a container that is not a docker container, you will not be able to access logs.
